version: 0.2

phases:
  pre_build:
    commands:
      - echo 'copying file'

  build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
    

